<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="MessagePack" Version="3.1.10" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.110" />
    <PackageVersion Include="Novolis.Transports.LocalIpc" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Markup.Markdown.Mermaid.Rendering" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Markup.Mermaid" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Markup.Mermaid.Rendering" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Maui.GraphicalProfile" Version="2026.1.*" />
    <PackageVersion Include="Novolis.IO.Ndjson" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Maui.Ndjson" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Maui.Agent" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Maui.Agent.Protocol" Version="2026.1.*" />
    <PackageVersion Include="TUnit" Version="1.72.4" />
  </ItemGroup>
</Project>
